server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.payroll: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:payroll}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: "9be370001@smtp-brevo.com"
    password: "3M8Cm1VaU7IN0wWH"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

app:
  mail:
    sender: "kishore.ayphen@gmail.com"
  security:
    jwt:
      secret: ${JWT_SECRET:c3VwZXItc2VjcmV0LWZvci1kZXZlbG9wbWVudC0xMjM0NTY3ODkwMTIzNDU2Nzg5MA==}
      expiration-minutes: ${JWT_EXP_MINUTES:1440}
